Suppress ruby warnings
x-motemen/git-pr-release pull request #59
Opened 2021-03-25 10:39 UTC by kachick

This PR just aims to remove ruby warnings.
But I bumped supported ruby version and dependency, because of clarify to use latest `erb`.
So if you think these change is meaningless in this gem, please just close this PR.  🙏 

Thanks for this useful tool!

---

I checked `bundle exec rspec` passed in following environments.

* ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
* ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux] # On docker `rubylang/ruby:2.5.8-bionic`, needs https://github.com/x-motemen/git-pr-release/pull/58
* ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-linux]  # On docker `rubylang/ruby:2.4.9-bionic` , needs https://github.com/x-motemen/git-pr-release/pull/58

2021-03-26 01:59 UTC, onk requested changes
It is acceptable except to use the latest `erb` gem.

How about drop support for ruby `<2.5` ?
`ERB#result_with_hash` is available in Ruby 2.5 and 2.4 is already EOL.

2021-03-26 01:59 UTC, onk commented on lib/git/pr/release/util.rb
> +          )
It's awesome to change `ERB#result(binding)` to `ERB#result_with_hash` !

Also bind other local variables.
I know that `changed_files` is often used in ERB templates.

2021-03-26 01:59 UTC, onk commented on lib/git/pr/release/util.rb
> +          erb = ERB.new template, trim_mode: '-'
IMO: This hack of checking Ruby version is commonly used in other gems.

e.g.
- https://github.com/rubocop/rubocop/blob/v1.12.0/lib/rubocop/cop/lint/erb_new_arguments.rb#L45-L60
- https://github.com/rails/rails/blob/v6.1.3/railties/lib/rails/generators/migration.rb#L66-L70
- https://github.com/rtomayko/tilt/blob/v2.0.10/lib/tilt/erb.rb#L24-L28

2021-03-26 06:00 UTC, kachick commented
Thanks for your review! I'll check and update. Temporally make be draft state. 🙇

2023-02-14 07:11 UTC, kachick commented
Sorry to keep draft state in longtime.
Looks conflicting with upstream, please let me close 🙇‍♂️

2023-02-14 07:11 UTC, closed without merging